language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4


matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true

before_install:
    - echo "$TRAVIS_PHP_VERSION"
    - rm composer.lock # this is a trick to download the correct phpunit version for all PHP versions

install:
    - composer install --dev --no-interaction


script:
    - mkdir -p build/logs
    - composer test
    - mv build/logs/clover.xml ./coverage.xml


after_success:
    - bash <(curl -s https://codecov.io/bash)